name: Build ExoPlayer FFmpeg

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Fetch ExoPlayer repository
        run: |
          cd "$GITHUB_WORKSPACE"
          # git clone https://github.com/google/ExoPlayer.git -b release-v2
          cd ExoPlayer
          FFMPEG_MODULE_PATH="$(pwd)/extensions/ffmpeg/src/main"
          cd "$GITHUB_WORKSPACE"
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip android-ndk-r21e-linux-x86_64.zip
          rm android-ndk-r21e-linux-x86_64.zip
          NDK_PATH="$GITHUB_WORKSPACE"/android-ndk-r21e      
          HOST_PLATFORM="linux-x86_64"
          # ANDROID_ABI=21
          cd "$GITHUB_WORKSPACE"
          git clone git://source.ffmpeg.org/ffmpeg
          cd ffmpeg
          git checkout release/4.2
          FFMPEG_PATH="$(pwd)"
          cd "$GITHUB_WORKSPACE"
          ENABLED_DECODERS=(alac ape)
          cd "${FFMPEG_MODULE_PATH}/jni"
          ln -s "$FFMPEG_PATH" ffmpeg
          chmod +x ./build_ffmpeg.sh
          ./build_ffmpeg.sh "${FFMPEG_MODULE_PATH}" "${NDK_PATH}" "${HOST_PLATFORM}" "${ENABLED_DECODERS[@]}"

      # - name: List all files in workspace
      #   run: find "$GITHUB_WORKSPACE" -type f -printf '%P\n' | sort

      - name: Check generated files
        run: ls -la "$GITHUB_WORKSPACE/ExoPlayer/extensions/ffmpeg/src/main/jni/ffmpeg/android-libs/"
  
      - name: Upload ExoPlayer FFmpeg
        uses: actions/upload-artifact@v4
        with:
          name: ExoPlayer FFmpeg
          path: ExoPlayer/extensions/ffmpeg/src/main/jni/ffmpeg/android-libs/*
